### ISSUE TITLE
Dai.js Interactive notebook

### ISSUE THREAD

**Issue by jparklev** [AndrewKirillo/bab-stablecoin_sims_research#8]
Heya -- 

I stumbled upon your project late at night looking at the dai.js dependents and thought I'd drop by to share this jupyter-like dai.js notebook: https://observablehq.com/@jparklev/dai-js-interactive Feel free to fork it or edit it there. My sense is that it might be useful for what you're doing, but if not, no worries -- don't mind me

**Comment by AndrewKirillo** [comment]
Wow, thank you! Will definitely take a look at this, and appreciate you checking out the project 😁
